# くコ:彡 www.nabilk.com single page theme 2019.11.24 くコ:彡

title: n a b i l k
email: n@nabilk.com
description: >-
  nabil kashyap
baseurl: ""
url: ""
twitter_username: _nabilk
github_username:  bulbil

# Build settings
theme: nabilk
# plugins:
  # - jemoji

sass:
  style: compressed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
  - README.md
  - LICENSE.txt
  - "*.gemspec"